config/routes.rb
Qa::Application.routes.draw do

  resources :questions do
    member { post :vote }
    resources :comments
  end
  resources :users
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :answers do
    member { post :vote }
  end
  
  root to: 'questions#index'
  match '/auth/:provider/callback' => 'authentications#create',  via: 'get'
  match '/signup',  to: 'users#new',                      via: 'get'
  match '/signin',  to: 'sessions#new',                   via: 'get'
  match '/signout', to: 'sessions#destroy',             via: 'delete'
  match '/help', to: 'static_pages#help',                via: 'get'
  match '/about', to: 'static_pages#about',            via: 'get'
  match '/contact', to: 'static_pages#contact',       via: 'get'
  match '/faq', to: 'static_pages#faq',       via: 'get'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :taggings
  has_many :comments, dependent: :destroy
  has_many :tags, through: :taggings
  has_one :visit, :as => :visitable
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true, length: { minimum: 10 , maximum: 200 }
  validates :body, presence: true, length: { minimum: 30 }
  validates :user_id, presence: true
  validates :tag_list, presence: true
  validates :tags, presence: true
  has_reputation :votes, source: :user, aggregated_by: :sum

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
    self.tags = new_or_found_tags
  end

  
  
  def self.search(search)
    if search && !search.blank? 
      find(:all, :conditions => ['body LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.search(params[:search]).paginate(page: params[:page])
    @users = User.paginate(page: params[:page])
    @tags = Tag.all
    @total_questions = Question.all
    @total_answers = Answer.all
    @total_comments = Comment.all
    @total_tags = Tag.all
    @total_users = User.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers
    @answer = @question.answers.build
    @question = Question.find(params[:id])
    Visit.track(@question, request.remote_ip)
    @comment = Comment.new
    @comment.question_id = @question.id
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:success] = t('controllers.questions.create.flash.success')
      redirect_to @question
    else
      render 'new'
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    if @question.update(question_params)
      flash[:success] = t('controllers.questions.update.flash.success')
      redirect_to @question
    else
      render  'edit'
    end  
  end
  
  

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    flash[:success] = t('controllers.questions.destroy.flash.success')
    redirect_to questions_url
  end
  
  def vote
    value = params[:type] == "up" ? 1 : -1
    @question = Question.find(params[:id])
    @question.add_or_update_evaluation(:votes, value, current_user)
    flash[:success] = t('controllers.questions.vote.flash.success')
    redirect_to :back
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end
        

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, :user_id, :tag_list, :question_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.erb
<div class="row rtl">
  <div class="span12">
    <p><%= t('.answers')%> ( <%= @question.answers.size.to_farsi %> )</p>
    <% @question.answers.each do |answer| %>
      <div class="row">
        <div class="span8">
          <span><i class="icon-user"></i>
  	    <%= link_to answer.user.name, answer.user %>
  	  </span>
          <span class="space"><i class="icon-calendar"></i>
  	    <%= to_jalali(answer.created_at) %>
  	  </span>       
          <% if  @answer.reputation_for(:votes).to_i >= 0 %>
            <span class="space"><i class="icon- icon-thumbs-up"></i>
            <%= t('.votes')%> <%= pluralize answer.reputation_for(:votes).to_i.to_farsi, "" %>
          <% else %>
            <span class="space"><i class="icon- icon-thumbs-down"></i>
            <%= t('.votes')%> <%= pluralize answer.reputation_for(:votes).to_i.to_farsi, "" %>
          <% end %>
          <% if current_user && !current_user.voted_for?(answer) %>
            <%= link_to "+", vote_answer_path(answer, type: "up"), method: "post" %>
    	    | <%= link_to "-", vote_answer_path(answer, type: "down"), method: "post" %>
  	  <% end %>
        </div>
        <div class="span2 offset2">
          <div class="pull-left">
            <% if current_user && current_user.admin? || current_user?(answer.user) %>
              <%= link_to t('.edit'), edit_answer_path(answer), class: "btn btn-small" %>
              <%= link_to t('.delete'), answer_path(answer), method: :delete,
    		  data: { confirm: "آیا مطمئن هستید؟" }, class: "btn btn-small btn-danger" %>
            <% end %>
          </div>
  	  <p class="top"></p>
	</div>
	<div class="span12">
   	  <%= sanitize answer.body %>
   	  <p></P><br/>
   	  <hr>
	</div>           
      </div>
    <% end %>
    <% if signed_in? %>
      <%= render partial: 'answers/answer' %>
    <% end %>
  </div>
</div>

app/views/questions/_comment.html.erb
<div class="row">
  <div class="span10 offset1 form-actions">
    <p><%= t('.comments') %> ( <%= @question.comments.size.to_farsi %> )</p>
  <small>
    <% @question.comments.each do |comment| %>
      <p id="comments">
        <%= comment.body %>
        <small class="space">
        <%= to_jalali(comment.created_at) %> 
        </small>
        <small class="space">
        <%= t('.by') %> <%= link_to comment.user.name, comment.user %>
        </small>
        <% if current_user && current_user.admin? || current_user?(comment.user) %>
          <%= link_to t('.edit'), edit_question_comment_path(@question, comment), class: "btn btn-mini" %>
          <%= link_to t('.delete'), [comment.question, comment],method: :delete,
    		data: { confirm: "آیا مطمئن هستید؟" }, class: "btn btn-mini btn-danger" %>
        <% end %>    
      </p>  
      <div class="row">
        <div class="span10">
          <hr>
        </div>
      </div>
    <% end %>
    <% if signed_in? %>
      <%= render partial: 'comments/form' %>  
    <% end %>
  </small>
  </div>
</div>
<hr>

app/views/questions/_form.html.erb
<% provide(:title, 'New Question') %>

<%= simple_form_for(@question,:html => { :novalidate => true }) do |f| %>
     
  <%= f.input :title, placeholder: t('.titleq'),
    :input_html => { :class => "span10" }, label: t('.title') %>
        
  <%= f.input :body, :input_html => { :class => "tinymce",rows: 15 }, label: t('.body') %>
  <%= tinymce %>
                
  <%= f.input :tag_list, placeholder: t('.tagq'), 
    :input_html => { :class => "span10" }, label: t('.tag') %><br/>
    
                
  <%= f.submit t('.submit'), class: "btn btn-medium btn-primary" %>
  <%= link_to t('.back'), questions_path, class: "btn" %>
<% end %>
 

app/views/questions/_question.html.erb
<h3><%= @question.title %></h3>
<div class="row">
  <div class="span8">
    <small>
      <span><i class="icon-user"></i> 
      <%= link_to @question.user.name, @question.user %></span>
      <span class="space"><i class="icon-calendar"></i> <%= to_jalali(@question.created_at) %></span>
      <span class="space"><i class="icon-comment"></i> 
         <%= t('.comments')%> <%= @question.comments.size.to_farsi %>
      </span>
      <span class="space"><i class="icon-eye-open"></i>
        <%= t('.views')%> <%= @question.visit.total_visits.to_farsi rescue 0 %>
      </span>
      <span class="space"><i class="icon-pencil"></i> 
        <%= t('.answers')%> <%= @question.answers.count.to_farsi %>
      </span>
        <% if  @question.reputation_for(:votes).to_i >= 0 %>
          <span class="space"><i class="icon- icon-thumbs-up"></i>
          <%= t('.votes')%> <%= pluralize @question.reputation_for(:votes).to_i.to_farsi, "" %>
        <% else %>
          <span class="space"><i class="icon- icon-thumbs-down"></i>
          <%= t('.votes')%> <%= pluralize @question.reputation_for(:votes).to_i.to_farsi, "" %>
        <% end %>
          
        <% if current_user && !current_user.voted_for?(@question) %>
          <%= link_to "+", vote_question_path(@question, type: "up"), method: "post" %>
          | <%= link_to "-", vote_question_path(@question, type: "down"), method: "post" %>
        <% end %>
    </small>
  </div>
  <div class="span3 offset1">
    <% if current_user && current_user.admin? || current_user?(@question.user) %>
      <div class="pull-left">
        <%= link_to t('.edit'), edit_question_path(@question), class: "btn btn-small" %> 
        <%= link_to t('.back'), questions_path, class: "btn btn-small" %>
        <%= link_to t('.delete'), @question, method: :delete,
    		data: { confirm: "آیا مطمئن هستید؟" }, class: "btn btn-small btn-danger" %>
      </div>
    <% end %>
  <p class="top"></p>
  </div>
  <div class="span12">
    <%= sanitize @question.body %>
  <p></p>
  </div>
  <div class="span12">
    <% @question.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag), class: "label label-info" %>
    <% end %>
  </div>
</div>
<hr>  

app/views/questions/_summary.html.erb
<% if @questions && @questions.empty? %>
  <strong>پرسشی پیدا نشد.</strong>
<% else %>
<% @questions.each do |question| %>
    <div class="row">
    <div class="span12" id="questions">
      <div class="row">
        <div class="span3">
        <li class="span1 well well-small digit">
          <span><%= pluralize question.reputation_for(:votes).to_i.to_farsi, "" %></span><br/>
          <span><%= t('.votes')%></span>
        </li>
        <li class="span1 well well-small digit">
          <span><%= question.answers.count.to_farsi %></span><br/>
          <span><%= t('.answers')%></span>
        </li>
        <li class="span1 well well-small digit">
          <span><%= question.visit.total_visits.to_farsi rescue 0 %></span><br/>
          <span><%= t('.views')%></span>
        </li>
        </div>
      <div class="span9" id="question">
        <h4><strong><%= link_to question.title, question_path(question) %></strong></h4>
          <p>
          <small>
            <% question.tags.each do |tag| %>
                 <%= link_to tag.name, tag_path(tag), class: "label label-info" %>
            <% end %>
            <span class="space"><i class="icon-user"></i> 
              <%= link_to question.user.name, question.user %>
            </span>
            <span class="space"><i class="icon-calendar"></i> 
              <%= to_jalali(question.created_at) %>
            </span>
          </small>
          </p>        
      </div>
      </div>
      <hr>
    </div>
    </div>
<% end %>
<% end %>

app/views/questions/_unanswer.html.erb
<% @questions.each do |question| %>
  <% if question.answers.count == 0 %>
    <div class="row">
    <div class="span12" id="questions">
      <div class="row">
        <div class="span3">      
        <li class="span1 well well-small digit">
          <span><%= pluralize question.reputation_for(:votes).to_i.to_farsi, "" %></span><br/>
          <span><%= t('.votes')%></span>
        </li>
        <li class="span1 well well-small digit">
          <span><%= question.answers.count.to_farsi %></span><br/>
          <span><%= t('.answers')%></span> 
        </li>
        <li class="span1 well well-small digit">
          <span><%= question.visit.total_visits.to_farsi rescue 0 %></span><br/>
          <span><%= t('.views')%></span>
        </li>
      </div>
      <div class="span9" id="question">
        <h4><strong><%= link_to question.title, question_path(question) %></strong></h4>
          <p>
          <small>
            <% question.tags.each do |tag| %>
                 <%= link_to tag.name, tag_path(tag), class: "label label-info" %>
            <% end %>
            <span class="space"><i class="icon-user"></i> 
              <%= link_to question.user.name, question.user %>
            </span>
            <span class="space"><i class="icon-calendar"></i> 
              <%= to_jalali(question.created_at) %>
            </span>
           </small>
          </p>
      </div>
      </div>
      <hr>
    </div>
    </div>
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<% provide(:tilte, 'Edit Question') %>
<div class="row rtl">
  <div class="span10 offset1 well">
  <legend><strong><%= t('.head') %></strong></legend>
    <p>
      <%= t('.create')%>
      <%= link_to @question.user.name, @question.user %>
      <small class="space">( <%= to_jalali(@question.created_at) %> )</small>
    </p>
  <p style="padding-top:5px"></p>
  <%= simple_form_for @question do |f| %> 
        <%= f.input :title, :input_html => { :class => "span10 " }, label: t('.title') %>
        
        <%= f.input :body, :input_html => { :class => "tinymce",rows: 15 }, label: t('.body') %>
        <%= tinymce %>
                
        <%= f.input :tag_list, :input_html => { :class => "span10" }, label: t('.tag') %><br/>
                
        <%= f.submit t('.submit'), class: "btn btn btn-warning" %>
        
        <%= link_to t('.back'), @question, class: "btn" %>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<% provide(:title) %>
<div class="row">  
  <div class="span4">
    <%= form_tag questions_path, :method => 'get' do %>
      <p class="pull-right">
        <%= text_field_tag :search, params[:search], class: "search-query span3" %>
        <%= submit_tag t('.search'), :name => nil, class: "btn" %>
      </p>
    <% end %>
  </div>
  <div class="span2 offset5 pull-left">
    <% if signed_in? %>
      <%= link_to t('.askquestion'), "questions/new", class: "btn btn-primary" %>
    <% else %>
      <%= link_to t('.askquestion'), "", class: "btn btn-primary disabled" %>
    <% end %>
  </div>
</div><br>
<div class="row offset1">
  <strong>
    <div class="span2">
      <p class="pull-right"><%= t('.questions') %> ( <%= @total_questions.count.to_farsi %> )</p>
    </div>
    <div class="span2">
      <p class="pull-right"><%= t('.answers') %> ( <%= @total_answers.count.to_farsi %> )</p>
    </div>
    <div class="span2">
      <p class="pull-right"><%= t('.comments') %> ( <%= @total_comments.count.to_farsi %> )</p>
    </div>
    <div class="span2">
      <p class="pull-right"><%= t('.tags') %> ( <%= @total_tags.count.to_farsi %> )</p>
    </div>
    <div class="span2">
      <p class="pull-right"><%= t('.users') %> ( <%= @total_users.count.to_farsi %> )</p>
    </div>
  </strong>
</div><br>
<div class="tabbable rtl">
  <ul class="nav nav-tabs">
    <li class="active  offset1"><a href="#tab1" data-toggle="tab"><%= t('.questions') %></a></li>
    <li><a href="#tab2" data-toggle="tab"><%= t('.users') %></a></li>
    <li><a href="#tab3" data-toggle="tab"><%= t('.tags') %></a></li>
    <li><a href="#tab4" data-toggle="tab"><%= t('.unanswered') %></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= render partial: 'summary' %>
    </div>
    <div class="tab-pane" id="tab2">
      <%= render partial: "users/user", collection: @users %>
      <%= will_paginate @users %>
      
    </div>
    <div class="tab-pane" id="tab3">
      <%= render partial: 'tags/index' %>
    </div>
    <div class="tab-pane" id="tab4">
      <%= render partial: 'unanswer' %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="row rtl">
  <div class="span10 offset1">
  <legend><strong><%= t('.head') %></strong></legend>
  <%= render 'form' %>
  </div>
</div>

app/views/questions/show.html.erb
<% provide(:title,)%>
<p id="notice"><%= notice %></p>
<div class="row rtl">
  <div class="span12">
    <%= render partial: 'questions/question' %>
    
    <%= render partial: 'questions/comment' %>
    </br> 
    <%= render partial: 'questions/answer' %>
  </div>
</div>