config/routes.rb
Qa::Application.routes.draw do

  resources :questions do
    member { post :vote }
    resources :comments
  end
  resources :users
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :answers do
    member { post :vote }
  end
  
  root to: 'questions#index'
  match '/auth/:provider/callback' => 'authentications#create',  via: 'get'
  match '/signup',  to: 'users#new',                      via: 'get'
  match '/signin',  to: 'sessions#new',                   via: 'get'
  match '/signout', to: 'sessions#destroy',             via: 'delete'
  match '/help', to: 'static_pages#help',                via: 'get'
  match '/about', to: 'static_pages#about',            via: 'get'
  match '/contact', to: 'static_pages#contact',       via: 'get'
  match '/faq', to: 'static_pages#faq',       via: 'get'

  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    flash[:success] = t('controllers.password_resets.create.flash.success')
    redirect_to root_url
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => t('controllers.password_resets.update.flash.fail')
    elsif @user.update_attributes(user_params)
      flash[:success] = t('controllers.password_resets.update.flash.success')
      redirect_to root_url
    else
      render :edit
    end
  end
  
  private
  
    def user_params
        params.require(:user).permit(:password, :password_confirmation)
    end
  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="row rtl">
  <legend class="span5"><%= t('.title') %></legend>
</div>
<div class="row rtl">
  <div class="span5">
    <%= simple_form_for @user, url: password_reset_path(params[:id]),
                    :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.input :password, :wrapper => :prepend, label: t('.password') do %>
    <span class="add-on"><i class="icon-lock"></i></span>
    <%= f.input_field :password, placeholder: t('.passwordl') %>
  <% end %>

  <%= f.input :password_confirmation, :wrapper => :prepend, label: t('.cpassword') do %>
    <span class="add-on"><i class="icon-lock"></i></span>
    <%= f.input_field :password_confirmation, placeholder: t('.passwordl') %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, t('.title'), :class => 'btn-primary' %>
  </div>

<% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="row rtl">
  <legend class="span4"><%= t('.title') %></legend>
</div>
<div class="row rtl">
  <div class="span3">
    <%= form_tag password_resets_path, method: :post do %>
      <div class="control-group email optional">
          <label class="email control-label">ایمیل</label>
          <div class="controls">
              <div class="input-prepend">
                <span class="add-on"><i class="icon-envelope"></i></span>
                <%= email_field_tag :email, params[:email], class: "string email" %>
              </div>
          </div>
        </div>
      <div class="actions"><%= submit_tag t('.reset_password'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>