config/routes.rb
Qa::Application.routes.draw do

  resources :questions do
    member { post :vote }
    resources :comments
  end
  resources :users
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :answers do
    member { post :vote }
  end
  
  root to: 'questions#index'
  match '/auth/:provider/callback' => 'authentications#create',  via: 'get'
  match '/signup',  to: 'users#new',                      via: 'get'
  match '/signin',  to: 'sessions#new',                   via: 'get'
  match '/signout', to: 'sessions#destroy',             via: 'delete'
  match '/help', to: 'static_pages#help',                via: 'get'
  match '/about', to: 'static_pages#about',            via: 'get'
  match '/contact', to: 'static_pages#contact',       via: 'get'
  match '/faq', to: 'static_pages#faq',       via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
     <a href="https://github.com/AR-H">AR-H</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('.about'), about_path %></li>
      <li><%= link_to t('.contact'), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </a>
      <%= link_to t('.brand_name'), root_path, class: "brand" %>  
      <div class="nav-collapse collapse">
	<ul class="nav pull-left">
	  <li><%= link_to t('.faq'), faq_path %></li>
	  <li class="divider-vertical"></li>
	  <li><%= link_to t('.contact'), contact_path %></li>
	  <li class="divider-vertical"></li>
	  <% if signed_in? %>
	    <div class="btn-group pull-right rtl">
	    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	      <i class="icon-user"></i> <%= current_user.name %> <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li><%= link_to t('.profile'), current_user %></li>
	      <li><%= link_to t('.settings'), edit_user_path(current_user) %></li>
	      <li class="divider"></li>
	      <li><%= link_to t('.signout'), signout_path, method: "delete" %></li>
	    </ul>
            </div>
	  <% else %>
	    <li><%= link_to t('.signin'), signin_path %></li>
	    <li class="divider-vertical"></li>
            <li><%= link_to t('.signup'), signup_path %></li>
	    <li class="divider-vertical"></li>
	    
	  <% end %>	  
	</ul>
      </div>
      <!--/.nav-collapse -->
    </div>
    <!--/.container -->
  </div>
  <!--/.navbar-inner -->
</div>
<!--/.navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key} rtl") %>
    <% end %>
    <%= yield %>
    
  </div>
</body>
</html>